# SPDX-License-Identifier: Apache-2.0
---
name: 'java-setup-gradle'
description: 'java-setup-gradle'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4