# SPDX-License-Identifier: Apache-2.0
---
name: 'java-setup-gradle'
description: 'java-setup-gradle'

inputs:
  DISTRIBUTION:
    description: "jdk distribution to use"
    required: false
    default: 'temurin'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: '${{ inputs.DISTRIBUTION }}'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/versions.gradle') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/versions.gradle') }}
          ${{ runner.os }}-gradle-
