# SPDX-License-Identifier: Apache-2.0
---
name: 'MetaMask Security Code Scanner'
description: 'MetaMask Security Code Scanner'

inputs:
  SECURITY_SCAN_METRICS_TOKEN:
    description: 'Metrics token'
    required: true
  APPSEC_BOT_SLACK_WEBHOOK:
    description: 'Slack webhook'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: Consensys/github-actions
        path: .github-actions

    # latest main (no releases; pinned 2026-03-21)
    - name: MetaMask Security Code Scanner
      uses: MetaMask/Security-Code-Scanner@5a08cec8d2a944cfe3bd86209a290af52e49a99c
      with:
        repo: ${{ github.repository }}
        paths_ignored: |
          .storybook/
          '**/__snapshots__/'
          '**/*.snap'
          '**/*.stories.js'
          '**/*.stories.tsx'
          '**/*.test.browser.ts*'
          '**/*.test.js*'
          '**/*.test.ts*'
          '**/fixtures/'
          '**/jest.config.js'
          '**/jest.environment.js'
          '**/mocks/'
          '**/test*/'
          docs/
          e2e/
          merged-packages/
          node_modules
          storybook/
          test*/
        rules_excluded: example
        project_metrics_token: ${{ inputs.SECURITY_SCAN_METRICS_TOKEN }}
        slack_webhook: ${{ inputs.APPSEC_BOT_SLACK_WEBHOOK }}
