# SPDX-License-Identifier: Apache-2.0
---
name: 'Trivy'
description: 'Composite action to run trivy on the npm package.json'


inputs:
  TRIVY_SKIP_DB_UPDATE:
    description: "Whether trivy should use cache instead of pulling latest db"
    required: false
    default: true
  TRIVY_SKIP_JAVA_DB_UPDATE:
    description: "Whether trivy should use cache instead of pulling latest java db"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v5
      with:
        repository: Consensys/github-actions
        path: .github-actions

    # v0.33.1
    # Refer to https://github.com/aquasecurity/trivy-action#updating-caches-in-the-default-branch for the env vars 
    # also uses aquasecurity/setup-trivy@v0.2.4
    # For MM you need to submit the hash for trivy-action and the VERSION (not hash) of setup-trivy. `setup-trivy` is slurped 
    # in via trivy-action and a hash won't work (maybe this is a bug with GH?) 
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.33.1
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
        cache: 'true'
      env:
        TRIVY_SKIP_DB_UPDATE: ${{ inputs.TRIVY_SKIP_DB_UPDATE && inputs.TRIVY_SKIP_DB_UPDATE != 'false' }}
        TRIVY_SKIP_JAVA_DB_UPDATE: ${{ inputs.TRIVY_SKIP_JAVA_DB_UPDATE && inputs.TRIVY_SKIP_JAVA_DB_UPDATE != 'false' }}

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
  