# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependency Review'

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/github-actions
        path: .github-actions

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high
        deny-licenses: LGPL-2.0, BSD-2-Clause
