# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependency Review'

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        repository: Consensys/github-actions
        path: .github-actions

    - name: Dependency Review
      uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
      with:
        fail-on-severity: high
        deny-licenses: LGPL-2.0, BSD-2-Clause
