# SPDX-License-Identifier: Apache-2.0
---
name: 'delete a pr preview on github pages'
description: 'Composite action to deploy to github pages'

inputs:
  GITHUB_TOKEN:
    description: 'Github secret Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get additional Github env vars # vars from Github env, can not be modified by users
      uses: FranzDiebold/github-env-vars-action@v2

    - name: generate PR slug
      shell: sh
      id: generate_pr_slug
      run: echo "::set-output name=slug::PR-${{ github.event.number }}"         

    - name: Delete preview
      shell: sh
      run: |
        rm -Rf "${{ steps.generate_pr_slug.outputs.slug }}"        

    - name: Commit and push to pages current branch
      shell: sh
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git commit -am "Automated deletion"
        git push

    - name: Remove comment to preview doc link
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: preview
        delete: true
