# SPDX-License-Identifier: Apache-2.0
---
name: 'test: links'
description: 'Composite action to validate links'

inputs:
  CONFIG_FILE:
    description: 'default config file.'
    required: false
    default: .github-actions/docs-link-check/config/.linkspector.yml

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/github-actions
        path: .github-actions

    # 5c5dfc0ac2e225883c0e5f03a85311ec2830d368 = v1 as at 24092024
    # use-quiet-mode: only show errors in output
    # use-verbose-mode: show detailed HTTP status for checked links
    - name: Test links
      uses: umbrelladocs/action-linkspector@v1
      with:
        config_file: ${{ inputs.CONFIG_FILE }}
