# SPDX-License-Identifier: Apache-2.0
---
name: 'test: links'
description: 'Composite action to validate links'

inputs:
  CONFIG_FILE:
    description: 'default config file.'
    required: false
    default: .github-actions/docs-link-check/config/.linkspector.yml
runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v6
      with:
        repository: Consensys/github-actions
        path: .github-actions

    - name: Use Node.js 
      uses: actions/setup-node@v6
      with:
        node-version: 20

    # Fix Chrome sandbox issues on Ubuntu 24.04
    - name: Setup Chrome Linux Sandbox
      shell: bash    
      run: |
        # Based on https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
        if [ "$(lsb_release -rs)" = "24.04" ]; then
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
          echo 'Done'
        else
          echo "Not running on Ubuntu 24.04 — skipping sandbox fix"
        fi

    - name: Install linkspector
      shell: bash
      run: |
        npm install -g @umbrelladocs/linkspector@0.4.7
    
    # Run linkspector and fail if there are broken links
    - name: Run linkspector
      shell: bash    
      run: |
        set -eo pipefail
        linkspector --version
        echo "🔍 Checking for broken links..."
        linkspector check -c ${{ inputs.CONFIG_FILE }}
        
