# SPDX-License-Identifier: Apache-2.0
---
name: 'test: links'
description: 'Composite action to validate links'

inputs:
  CONFIG_FILE:
    description: 'default config file.'
    required: false
    default: .github-actions/docs-link-check/config/.linkspector.yml

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v5
      with:
        repository: Consensys/github-actions
        path: .github-actions

    # umbrelladocs/action-linkspector@v1
    # use-quiet-mode: only show errors in output
    # use-verbose-mode: show detailed HTTP status for checked links
    - name: Test links
      uses: umbrelladocs/action-linkspector@652f85bc57bb1e7d4327260decc10aa68f7694c3
      with:
        config_file: ${{ inputs.CONFIG_FILE }}
