# SPDX-License-Identifier: Apache-2.0
---
name: 'test: links'
description: 'Composite action to validate links'

inputs:
  CONFIG_FILE:
    description: 'default config file.'
    required: false
    default: .github-actions/docs-link-check/config/.linkspector.yml
  FAIL_LEVEL:
    description: 'exit code for reviewdog when errors are found with severity greater than or equal to this level'
    required: false
    default: 'any'
  FILTER_MODE:
    description: 'filtering mode for reviewdog command'
    required: false
    default: 'nofilter'
runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v5
      with:
        repository: Consensys/github-actions
        path: .github-actions

    - name: Test links
      uses: umbrelladocs/action-linkspector@652f85bc57bb1e7d4327260decc10aa68f7694c3
      with:
        config_file: ${{ inputs.CONFIG_FILE }}
        fail_level: ${{ inputs.FAIL_LEVEL }}
        filter_mode: ${{ inputs.FILTER_MODE }}
