name: sync_gha_allowlist

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  update-allowlist:
    runs-on: ubuntu-24.04
    environment: security
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Update the repo allowlist
        uses: ConsenSys/github-actions/sync-repo-allowlist@main # main
        with:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
